AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: s3://benkeil-cloudformation/595ffd1ada5740140cfbe552e4e90639
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get
Outputs:
  Endpoint:
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
