---
AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: .
      Timeout: 10
      Environment:
        Variables:
          # we can also use docker networks to connect via localhost
          LOCALSTACK_URL: "http://192.168.178.21"
          QUEUE_ID: "hello-queue"
          QUEUE_URL: "http://192.168.178.21:4576/queue/hello-queue"
      Events:
        HelloEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  Endpoint:
    Value:  !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"